### ISSUE TITLE
AttributeError: module 'pyvirtualcam' has no attribute 'Camera'

### ISSUE THREAD

**Issue by RemingtonKim** [letmaik/pyvirtualcam#7]
I am trying to use pyvirtualcam to set up a virtual camera; however, I get this error every time I try to run my code.

`AttributeError: module 'pyvirtualcam' has no attribute 'Camera'`

I have installed obs-virtualcam and all necessary dependencies, but this error still occurs. Does anyone know why this is happening?

**Comment by letmaik** [comment]
Can you give more details on your environment and how you installed the package? It is unlikely an issue with the package.

**Comment by RemingtonKim** [comment]
I ended up figuring out what the issue was. I was working in a python 3.5 environment, which was causing the error. Once I upgraded to python 3.6, everything worked smoothly. Cheers!
